### ISSUE TITLE
TitleContainer is never used.

### ISSUE THREAD

**Issue by whitef0x0** [alecortega/palettable#11]
Looking through the source it seems like TitleContainer is never used. Are you about to use it for a new feature or should I remove it? @alecortega

**Comment by alec-chernicki** [comment]
`TitleContainer` is the is the container component for `Title` which is the presentational component. It passes the first color so that `Title` changes color based on the luminosity of the first color that's been chosen.

**Comment by whitef0x0** [comment]
oh ok nvm
