### ISSUE TITLE
Tutorial button does nothing

### ISSUE THREAD

**Issue by whitef0x0** [alecortega/palettable#5]
What is the tutorial button supposed to link to? Like an interactive tutorial ala Slack?

**Comment by alec-chernicki** [comment]
It should kick off the onboarding tutorial on how to use the app. On click it resets your palette then shows the first screen of the tutorial. If you could attach a screen capture or console log if you're getting an error that would be helpful!

**Comment by whitef0x0** [comment]
nvm my bad
